name: resort_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.1.0
  image_cropper: ^5.0.1
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.3
  responsive_sizer: ^3.3.1
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true